### ISSUE TITLE
About page

### ISSUE THREAD

**Issue by milesgranger** [milesgranger/hemlock-highway#5]
Create an about page to easily explain what this is all about.

**Comment by joakimgk** [comment]
Let's meet soon! :-)

**Comment by joakimgk** [comment]
Sorry, didn't mean to close the issue :-D Not so experienced with the github.com ui

**Comment by joakimgk** [comment]
Sorry, didn't mean to close the issue :-D Not so experienced with the github.com ui

**Comment by milesgranger** [comment]
Haha! @joakimgk Let's do it! You name the time and place, I'm pretty sure I can meet any day except the 10th and 11th. :+1:  

_Sent from my Samsung SM-G935F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
